# Generated by Django 4.2.1 on 2023-06-24 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('imagen', models.CharField(max_length=120)),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.CharField(max_length=300)),
                ('valor', models.IntegerField()),
            ],
            options={
                'db_table': 'producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='contacto',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('apellido', models.CharField(max_length=120)),
                ('mail', models.CharField(max_length=120)),
                ('contrasena', models.CharField(max_length=120)),
            ],
        ),
    ]
