# Generated by Django 4.2.1 on 2023-06-27 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dcarmelita', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fotos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_archivo', models.CharField(max_length=120)),
                ('imagen_real', models.ImageField(upload_to='../static/img/')),
            ],
            options={
                'db_table': 'fotos',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='contacto',
        ),
    ]
