# Generated by Django 4.2.1 on 2023-06-27 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dcarmelita', '0002_fotos_delete_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotos',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fotos',
            name='imagen_real',
            field=models.ImageField(upload_to='Dcarmelita/static/img/'),
        ),
    ]
