# Generated by Django 4.2.1 on 2023-06-27 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dcarmelita', '0003_alter_fotos_id_alter_fotos_imagen_real'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'managed': True},
        ),
    ]
