# Generated by Django 4.2.1 on 2023-06-27 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dcarmelita', '0004_alter_producto_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
